# 1. test a small dataset with easy config

bids_dir=/mnt/DataDrive3/swap/test_brainana/raw/dataset_easy_downsampled_multianat
output_dir=/mnt/DataDrive3/swap/test_brainana/preproc/dataset_easy_downsampled_multianat
config_file=/mnt/DataDrive3/swap/test_brainana/config_easy.yaml

fs_license=/usr/local/freesurfer/7.4.1/license_Mike.txt

docker run --rm -t --gpus all \
    -v "$bids_dir":/input \
    -v "$output_dir":/output \
    -v "$config_file":/config.yaml \
    -v "$fs_license":/fs_license.txt \
    brainana:latest \
    /input /output/preprocessed \
    -w /output/preprocessed_wd \
    --config /config.yaml \
    --freesurfer-license /fs_license.txt


# 2. test a real dataset with costom config
# change the bids_dir, output_dir, and config_file (could be generated by ./config_generator.html)