/*
 * Configuration helper functions for Nextflow workflows
 * 
 * Provides utilities for parameter resolver initialization and config file management.
 * 
 * Load this file with: def configHelpers = evaluate(new File("${projectDir}/workflows/config_helpers.groovy").text)
 */

/**
 * Ensure parameter resolver is initialized
 * 
 * Safe to call multiple times - will only initialize once due to internal caching.
 * This should be called at the start of each workflow to ensure parameter resolution is available.
 * 
 * @param paramResolver Parameter resolver instance (from param_resolver.groovy)
 * @param params Nextflow params object
 * @param projectDir Project directory path
 * @throws RuntimeException if initialization fails
 */
def ensureParamResolverInitialized = { paramResolver, params, projectDir ->
    try {
        paramResolver.initialize(params, projectDir)
    } catch (Exception e) {
        error "Failed to initialize parameter resolver: ${e.message}"
    }
}

/**
 * Get effective config file path (as string, not file object)
 * 
 * Returns the path string - convert to file() only inside processes.
 * Note: This assumes the config file has already been generated by generateEffectiveConfig in main.nf
 * 
 * This function ensures the file exists before returning the path.
 * If the file doesn't exist, it will error with a helpful message.
 * 
 * @param params Nextflow params object (must contain output_dir)
 * @param projectDir Project directory path
 * @return String path to effective config file: "${params.output_dir}/nextflow_reports/config.yaml"
 * @throws RuntimeException if config file doesn't exist
 */
def getEffectiveConfigPath = { params, projectDir ->
    def effective_config_path = "${params.output_dir}/nextflow_reports/config.yaml"
    
    // Ensure directory exists
    def config_dir = new File("${params.output_dir}/nextflow_reports")
    if (!config_dir.exists()) {
        config_dir.mkdirs()
    }
    
    // Check if file exists
    def config_file_path = new File(effective_config_path)
    if (!config_file_path.exists()) {
        error "Effective config file not found: ${effective_config_path}\n" +
              "This file should have been generated by generateEffectiveConfig() in main.nf.\n" +
              "Make sure parameter resolver is initialized before workflows are invoked."
    }
    
    return effective_config_path
}

/**
 * Get boolean value from YAML config file
 *
 * @param configPath Path to YAML config file (e.g. effective config)
 * @param keyPath Dot-separated key path (e.g. "registration.use_gpu")
 * @param defaultValue Default value when key not found
 * @return Boolean value
 */
def getConfigBool = { configPath, keyPath, defaultValue = false ->
    if (configPath == null || configPath.toString().trim().isEmpty()) {
        return defaultValue
    }
    def configFile = new File(configPath.toString())
    if (!configFile.exists()) {
        return defaultValue
    }
    try {
        def slurper = new groovy.yaml.YamlSlurper()
        def config = slurper.parse(configFile)
        def keys = keyPath.split('\\.')
        def value = config
        for (def key in keys) {
            if (value != null && value instanceof Map) {
                value = value.get(key)
            } else {
                return defaultValue
            }
        }
        return (value != null) ? (value == true) : defaultValue
    } catch (Exception e) {
        return defaultValue
    }
}

// Return helpers as a map
return [
    ensureParamResolverInitialized: ensureParamResolverInitialized,
    getEffectiveConfigPath: getEffectiveConfigPath,
    getConfigBool: getConfigBool
]
