/*
 * Configuration helper functions for Nextflow workflows
 * Load this file with: def configHelpers = evaluate(new File("${projectDir}/workflows/config_helpers.groovy").text)
 */

/**
 * Ensure parameter resolver is initialized
 * Safe to call multiple times - will only initialize once
 */
def ensureParamResolverInitialized = { paramResolver, params, projectDir ->
    try {
        paramResolver.initialize(params, projectDir)
    } catch (Exception e) {
        error "Failed to initialize parameter resolver: ${e.message}"
    }
}

/**
 * Get effective config file path (as string, not file object)
 * Returns the path string - convert to file() only inside processes
 * Note: This assumes the config file has already been generated by generateEffectiveConfig in main.nf
 * 
 * This function ensures the file exists before returning the path.
 * If the file doesn't exist, it will error with a helpful message.
 */
def getEffectiveConfigPath = { params, projectDir ->
    def effective_config_path = "${params.output_dir}/nextflow_reports/config.yaml"
    
    // Ensure directory exists
    def config_dir = new File("${params.output_dir}/nextflow_reports")
    if (!config_dir.exists()) {
        config_dir.mkdirs()
    }
    
    // Check if file exists
    def config_file_path = new File(effective_config_path)
    if (!config_file_path.exists()) {
        error "Effective config file not found: ${effective_config_path}\n" +
              "This file should have been generated by generateEffectiveConfig() in main.nf.\n" +
              "Make sure parameter resolver is initialized before workflows are invoked."
    }
    
    return effective_config_path
}

// Return helpers as a map
return [
    ensureParamResolverInitialized: ensureParamResolverInitialized,
    getEffectiveConfigPath: getEffectiveConfigPath
]
